[workspace]
members = ["agent", "cli", "manager", "operator", "proxy"]
resolver = "2"

[profile.release]
debug = false
debug-assertions = false
lto = true
opt-level = 's'
overflow-checks = false
panic = "unwind"
rpath = false
