[workspace]
members = [
    "manager",
    "agent",
    "cli",
    "proxy",
]
resolver = "2"

[profile.release]
opt-level = 's'
debug = false
rpath = false
debug-assertions = false
overflow-checks = false
lto = true
